### ISSUE TITLE
How to keep online

### ISSUE THREAD

**Issue by tkit1994** [hanbing0715/pySrun4k#2]
How to keep online.
如何保持在线状态，不掉线.

**Comment by phy25** [comment]
If your other session is logging out, your session may be kicked off regardless of network admin's session timeout options. So it might be better to write a "check status and login if necessary periodically" logic.

**Comment by tkit1994** [comment]
Any suggestions for overriding the network admin's session timeout options instead of 
> writing a "check status and login if necessary periodically" logic"

Because that can not keep the device online all the time.
In this C# project https://github.com/TscCai/FreeSrun/blob/master/FreeSrun/SrunService.cs#L54-L102, it sends a heartbeat packet to the admin server every certain minutes to avoid being kicked off by the network administrator. Unfortunately after our school's network upgrade from srun3k to srun4k. It fails to work.

有没有关于覆盖网络管理员会话超时选项的任何建议？而不是
>writing a "check status and login if necessary periodically" logic"

因为这无法使设备始终保持在线状态。
在这个C#项目https://github.com/TscCai/FreeSrun/blob/master/FreeSrun/SrunService.cs#L54-L102 中，它每隔几分钟就会向服务器发送一个心跳包，以避免被网络管理员踢下线。 不幸的是，我们学校的网络从srun3k升级到srun4k后, 它无法正常工作了。

**Comment by hanbing0715** [comment]
i'm sorry i leave school that use srun, and my school disable session timeout, for my use case, after login, no more thing need to do.
